import Link from "next/link"
import PracticeCategorySummaryList from "@/components/practice-diary/PracticeCategorySummaryList"
import PracticeFocusSummaryList from "@/components/practice-diary/PracticeFocusSummaryList"
import PracticeTuneSummaryList from "@/components/practice-diary/PracticeTuneSummaryList"
import { joinClasses } from "@/components/ui/buttonStyles"
import type { PracticeDiaryMonthData } from "@/lib/loaders/practice-diary"

type MonthTab = "calendar" | "tunes" | "focus" | "notes"
function tabFrom(value?: string): MonthTab { return value === "tunes" || value === "focus" || value === "notes" ? value : "calendar" }
function tabHref(data: PracticeDiaryMonthData, tab: MonthTab) { return `/review/diary?view=month&date=${data.selectedDate}&tab=${tab}` }
function activityClass(level: string, inMonth: boolean) { if (!inMonth) return "opacity-35 bg-background"; if (level === "heavy") return "bg-primary text-primary-foreground"; if (level === "medium") return "bg-accent/70 text-accent-foreground"; if (level === "light") return "bg-card text-foreground"; return "bg-background text-muted-foreground" }

export default function PracticeMonthView({ data, activeTab }: { data: PracticeDiaryMonthData; activeTab?: string }) {
  const tab = tabFrom(activeTab)
  return <div className="space-y-6">
    <nav aria-label="Month details" className="grid grid-cols-4 rounded-full border border-border bg-muted/60 p-1 sm:max-w-2xl">{(["calendar", "tunes", "focus", "notes"] as const).map((item) => <Link key={item} href={tabHref(data, item)} aria-current={tab === item ? "page" : undefined} className={joinClasses("flex min-h-11 items-center justify-center rounded-full px-2 text-xs font-semibold capitalize sm:text-sm focus:outline-none focus:ring-2 focus:ring-[var(--focus-ring)]", tab === item ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:text-foreground")}>{item}</Link>)}</nav>
    {tab === "calendar" ? <section aria-labelledby="month-map-heading">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="month-map-heading" className="text-sm font-semibold uppercase tracking-[0.16em] text-muted-foreground">Musical month</h2><p className="mt-2 text-sm text-muted-foreground">Colour shows practice volume; letters show the mix of Rough, Shaky, and Solid results.</p></div><p className="text-sm font-medium">{data.summary.activeDays} active days · {data.summary.uniqueTunesTouched} tunes</p></div>
      <div className="mt-5 grid grid-cols-7 gap-1.5 sm:gap-2">{(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] as const).map((day) => <div key={day} className="text-center text-[0.65rem] font-semibold uppercase text-muted-foreground sm:text-xs">{day}</div>)}{data.daySummaries.map((day) => { const summary = `${day.formalReviewCount + day.practiceCheckCount} entries, ${day.roughCount} Rough, ${day.shakyCount} Shaky, ${day.solidCount} Solid`; return <Link key={day.date} href={`/review/diary?view=day&date=${day.date}`} aria-label={`${day.date}: ${summary}`} className={joinClasses("min-h-16 rounded-xl border border-border p-1.5 text-center shadow-sm transition hover:-translate-y-0.5 focus:outline-none focus:ring-2 focus:ring-[var(--focus-ring)] sm:min-h-24 sm:p-2", activityClass(day.activityLevel, day.isInSelectedMonth), day.isToday ? "ring-2 ring-[var(--focus-ring)]" : "")}><span className="text-xs font-bold sm:text-sm">{Number(day.date.slice(-2))}</span>{day.hasPractice ? <span className="mt-1 block text-[0.58rem] font-semibold leading-4 sm:text-xs">R{day.roughCount} S{day.shakyCount} ✓{day.solidCount}</span> : null}</Link> })}</div>
      <div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground"><span>R = Rough</span><span>S = Shaky</span><span>✓ = Solid</span><span>Lighter → darker = more activity</span></div>
      <details className="mt-5 border-t border-border pt-4"><summary className="min-h-11 cursor-pointer font-semibold">Accessible text summary</summary><ul className="mt-2 divide-y divide-border">{data.daySummaries.filter((day) => day.isInSelectedMonth && day.hasPractice).map((day) => <li key={day.date} className="py-2 text-sm"><strong>{day.date}</strong>: {day.formalReviewCount + day.practiceCheckCount} entries; {day.roughCount} Rough, {day.shakyCount} Shaky, {day.solidCount} Solid; {day.noteCount} notes.</li>)}</ul></details>
    </section> : tab === "tunes" ? <section><h2 className="text-sm font-semibold uppercase tracking-[0.16em] text-muted-foreground">Most practised tunes</h2><PracticeTuneSummaryList summaries={data.tuneSummaries} emptyMessage="No tune practice has been logged this month yet." sortMode="mostPractised" /></section> : tab === "focus" ? <section><h2 className="text-sm font-semibold uppercase tracking-[0.16em] text-muted-foreground">Focus areas touched</h2><PracticeFocusSummaryList summaries={data.focusSummaries} emptyMessage="No focus-linked notes this month. Link a note to a focus area to see the pattern here." /></section> : <section><h2 className="text-sm font-semibold uppercase tracking-[0.16em] text-muted-foreground">Notes and patterns</h2><PracticeCategorySummaryList summaries={data.categorySummaries} emptyMessage="No categorised notes this month." /></section>}
  </div>
}
