create table if not exists public.learning_list_shares (
  id bigint generated by default as identity primary key,
  learning_list_id bigint not null references public.learning_lists(id) on delete cascade,
  shared_with_user_id uuid not null references public.profiles(id) on delete cascade,
  permission text not null default 'view',
  created_at timestamptz not null default now(),
  constraint learning_list_shares_permission_check check (permission = 'view'),
  constraint learning_list_shares_list_recipient_key unique (learning_list_id, shared_with_user_id)
);

create index if not exists learning_list_shares_recipient_idx
  on public.learning_list_shares (shared_with_user_id, created_at desc);

create index if not exists learning_list_shares_list_idx
  on public.learning_list_shares (learning_list_id);

alter table public.learning_list_shares enable row level security;

drop policy if exists "List owners and recipients can select list shares"
  on public.learning_list_shares;
create policy "List owners and recipients can select list shares"
  on public.learning_list_shares
  for select
  using (
    shared_with_user_id = auth.uid()
    or exists (
      select 1
      from public.learning_lists
      where learning_lists.id = learning_list_shares.learning_list_id
        and learning_lists.user_id = auth.uid()::text
    )
  );

drop policy if exists "List owners can insert list shares"
  on public.learning_list_shares;
create policy "List owners can insert list shares"
  on public.learning_list_shares
  for insert
  with check (
    shared_with_user_id <> auth.uid()
    and exists (
      select 1
      from public.learning_lists
      where learning_lists.id = learning_list_shares.learning_list_id
        and learning_lists.user_id = auth.uid()::text
    )
  );

drop policy if exists "List owners can delete list shares"
  on public.learning_list_shares;
create policy "List owners can delete list shares"
  on public.learning_list_shares
  for delete
  using (
    exists (
      select 1
      from public.learning_lists
      where learning_lists.id = learning_list_shares.learning_list_id
        and learning_lists.user_id = auth.uid()::text
    )
  );

drop policy if exists "Shared recipients can select learning lists"
  on public.learning_lists;
create policy "Shared recipients can select learning lists"
  on public.learning_lists
  for select
  using (
    exists (
      select 1
      from public.learning_list_shares
      where learning_list_shares.learning_list_id = learning_lists.id
        and learning_list_shares.shared_with_user_id = auth.uid()
    )
  );

drop policy if exists "Shared recipients can select learning list items"
  on public.learning_list_items;
create policy "Shared recipients can select learning list items"
  on public.learning_list_items
  for select
  using (
    exists (
      select 1
      from public.learning_list_shares
      where learning_list_shares.learning_list_id = learning_list_items.learning_list_id
        and learning_list_shares.shared_with_user_id = auth.uid()
    )
  );
