create table if not exists public.compare_invites (
  id bigint generated by default as identity primary key,
  creator_user_id uuid not null references auth.users(id) on delete cascade,
  token_hash text not null,
  expires_at timestamptz not null default (now() + interval '24 hours'),
  accepted_by_user_id uuid null references auth.users(id) on delete set null,
  accepted_at timestamptz null,
  revoked_at timestamptz null,
  connection_id bigint null references public.connections(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint compare_invites_token_hash_key unique (token_hash),
  constraint compare_invites_token_hash_format_check
    check (token_hash ~ '^[0-9a-f]{64}$'),
  constraint compare_invites_acceptance_check
    check (
      (accepted_at is null and accepted_by_user_id is null and connection_id is null)
      or
      (accepted_at is not null and accepted_by_user_id is not null and connection_id is not null)
    )
);

create unique index if not exists compare_invites_creator_pending_idx
  on public.compare_invites (creator_user_id)
  where accepted_at is null and revoked_at is null;

create index if not exists compare_invites_expiry_idx
  on public.compare_invites (expires_at)
  where accepted_at is null and revoked_at is null;

alter table public.compare_invites enable row level security;

revoke insert, update, delete on table public.compare_invites
  from anon, authenticated;
revoke select on table public.compare_invites from anon;
grant select on table public.compare_invites to authenticated;

drop policy if exists "Creators can select their own compare invitations"
  on public.compare_invites;
create policy "Creators can select their own compare invitations"
  on public.compare_invites
  for select
  to authenticated
  using (creator_user_id = auth.uid());

create or replace function public.accept_compare_invite(p_token_hash text)
returns table (
  invite_result text,
  compare_username text,
  compare_display_name text,
  connection_record_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_accepting_user_id uuid := auth.uid();
  v_invite public.compare_invites%rowtype;
  v_connection public.connections%rowtype;
  v_connection_was_accepted boolean := false;
  v_creator_username text;
  v_creator_display_name text;
  v_creator_can_compare boolean := false;
begin
  if v_accepting_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  if p_token_hash is null or p_token_hash !~ '^[0-9a-f]{64}$' then
    return query select 'invalid'::text, null::text, null::text, null::bigint;
    return;
  end if;

  select compare_invites.*
  into v_invite
  from public.compare_invites
  where compare_invites.token_hash = p_token_hash
  for update;

  if not found then
    return query select 'invalid'::text, null::text, null::text, null::bigint;
    return;
  end if;

  select
    profiles.username,
    profiles.display_name,
    profiles.show_compare_discoverability
  into
    v_creator_username,
    v_creator_display_name,
    v_creator_can_compare
  from public.profiles
  where profiles.id = v_invite.creator_user_id;

  if v_invite.creator_user_id = v_accepting_user_id then
    return query
    select 'self'::text, v_creator_username, v_creator_display_name, null::bigint;
    return;
  end if;

  if v_creator_username is null or not coalesce(v_creator_can_compare, false) then
    update public.compare_invites
    set revoked_at = coalesce(revoked_at, now())
    where id = v_invite.id
      and accepted_at is null;

    return query select 'revoked'::text, null::text, null::text, null::bigint;
    return;
  end if;

  if not exists (
    select 1
    from public.profiles
    where profiles.id = v_accepting_user_id
      and nullif(trim(profiles.username), '') is not null
      and profiles.show_compare_discoverability = true
  ) then
    return query
    select
      'profile_required'::text,
      v_creator_username,
      v_creator_display_name,
      null::bigint;
    return;
  end if;

  if v_invite.accepted_at is not null then
    if v_invite.accepted_by_user_id = v_accepting_user_id then
      return query
      select
        'accepted'::text,
        v_creator_username,
        v_creator_display_name,
        v_invite.connection_id;
    else
      return query select 'consumed'::text, null::text, null::text, null::bigint;
    end if;
    return;
  end if;

  if v_invite.revoked_at is not null then
    return query select 'revoked'::text, null::text, null::text, null::bigint;
    return;
  end if;

  if v_invite.expires_at <= now() then
    return query select 'expired'::text, null::text, null::text, null::bigint;
    return;
  end if;

  select connections.*
  into v_connection
  from public.connections
  where (
    connections.requester_id = v_invite.creator_user_id
    and connections.addressee_id = v_accepting_user_id
  ) or (
    connections.requester_id = v_accepting_user_id
    and connections.addressee_id = v_invite.creator_user_id
  )
  order by
    case when connections.status = 'accepted' then 0 else 1 end,
    connections.id
  limit 1
  for update;

  if found then
    v_connection_was_accepted := v_connection.status = 'accepted';

    if v_connection.status <> 'accepted' then
      update public.connections
      set
        status = 'accepted',
        accepted_at = coalesce(accepted_at, now())
      where id = v_connection.id;
    end if;
  else
    begin
      insert into public.connections (
        requester_id,
        addressee_id,
        status,
        accepted_at
      )
      values (
        v_invite.creator_user_id,
        v_accepting_user_id,
        'accepted',
        now()
      )
      returning * into v_connection;
    exception
      when unique_violation then
        select connections.*
        into v_connection
        from public.connections
        where (
          connections.requester_id = v_invite.creator_user_id
          and connections.addressee_id = v_accepting_user_id
        ) or (
          connections.requester_id = v_accepting_user_id
          and connections.addressee_id = v_invite.creator_user_id
        )
        order by
          case when connections.status = 'accepted' then 0 else 1 end,
          connections.id
        limit 1
        for update;

        if not found then
          raise;
        end if;

        if v_connection.status <> 'accepted' then
          update public.connections
          set
            status = 'accepted',
            accepted_at = coalesce(accepted_at, now())
          where id = v_connection.id;
        end if;
    end;
  end if;

  update public.compare_invites
  set
    accepted_by_user_id = v_accepting_user_id,
    accepted_at = now(),
    connection_id = v_connection.id
  where id = v_invite.id;

  return query
  select
    case
      when v_connection_was_accepted then 'already_connected'
      else 'accepted'
    end::text,
    v_creator_username,
    v_creator_display_name,
    v_connection.id;
end;
$$;

revoke all on function public.accept_compare_invite(text) from public;
grant execute on function public.accept_compare_invite(text) to authenticated;
