-- Festival hubs reference the existing learning-list catalogue. They do not own
-- tune membership, save state, practice state, media, or Compare data.
create table public.festival_hubs (
  id bigint generated by default as identity primary key,
  slug text not null unique check (
    char_length(slug) between 3 and 80
    and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
  ),
  name text not null check (char_length(btrim(name)) between 1 and 120),
  description text check (description is null or char_length(description) <= 4000),
  timezone text not null default 'Australia/Melbourne' check (char_length(timezone) between 1 and 100),
  branding_image_url text check (branding_image_url is null or branding_image_url ~ '^https://'),
  branding_alt text check (branding_alt is null or char_length(btrim(branding_alt)) between 1 and 240),
  programme_url text check (programme_url is null or programme_url ~ '^https://'),
  programme_snapshot_date date,
  curator_credit text check (curator_credit is null or char_length(btrim(curator_credit)) between 1 and 160),
  curator_profile_id uuid references public.profiles(id) on delete set null,
  lifecycle text not null default 'draft' check (lifecycle in ('draft', 'published', 'archived')),
  editorial_order integer not null default 0 check (editorial_order >= 0),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((branding_image_url is null) = (branding_alt is null))
);

create table public.festival_collections (
  id bigint generated by default as identity primary key,
  festival_id bigint not null references public.festival_hubs(id) on delete cascade,
  learning_list_id bigint not null references public.learning_lists(id) on delete restrict,
  collection_kind text not null default 'general' check (collection_kind in ('artist', 'tradition', 'general')),
  display_title text check (display_title is null or char_length(btrim(display_title)) between 1 and 160),
  display_credit text check (display_credit is null or char_length(btrim(display_credit)) between 1 and 160),
  profile_id uuid references public.profiles(id) on delete set null,
  tradition_label text check (tradition_label is null or char_length(btrim(tradition_label)) between 1 and 120),
  editorial_order integer not null default 0 check (editorial_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (festival_id, learning_list_id),
  unique (festival_id, id)
);

create table public.festival_sessions (
  id bigint generated by default as identity primary key,
  festival_id bigint not null references public.festival_hubs(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 160),
  leader_name text check (leader_name is null or char_length(btrim(leader_name)) between 1 and 160),
  leader_profile_id uuid references public.profiles(id) on delete set null,
  venue text check (venue is null or char_length(btrim(venue)) between 1 and 160),
  local_date date,
  local_start_time time,
  local_end_time time,
  status text not null default 'scheduled' check (status in ('scheduled', 'changed', 'cancelled')),
  source_note text check (source_note is null or char_length(source_note) <= 1000),
  needs_review boolean not null default false,
  editorial_order integer not null default 0 check (editorial_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (festival_id, id),
  check (local_end_time is null or local_start_time is not null)
);

create table public.festival_session_collections (
  festival_id bigint not null,
  session_id bigint not null,
  festival_collection_id bigint not null,
  editorial_order integer not null default 0 check (editorial_order >= 0),
  created_at timestamptz not null default now(),
  primary key (session_id, festival_collection_id),
  foreign key (festival_id, session_id)
    references public.festival_sessions(festival_id, id) on delete cascade,
  foreign key (festival_id, festival_collection_id)
    references public.festival_collections(festival_id, id) on delete cascade
);

create table public.festival_settings (
  singleton boolean primary key default true check (singleton),
  mode_enabled boolean not null default false,
  selected_festival_id bigint references public.festival_hubs(id) on delete set null,
  updated_at timestamptz not null default now(),
  check (not mode_enabled or selected_festival_id is not null)
);

insert into public.festival_settings (singleton, mode_enabled, selected_festival_id)
values (true, false, null)
on conflict (singleton) do nothing;

create index festival_hubs_public_order_idx
  on public.festival_hubs (lifecycle, editorial_order, id);
create index festival_collections_list_idx
  on public.festival_collections (learning_list_id);
create index festival_collections_order_idx
  on public.festival_collections (festival_id, editorial_order, id);
create index festival_sessions_order_idx
  on public.festival_sessions (festival_id, local_date, local_start_time, editorial_order, id);
create index festival_sessions_leader_profile_idx
  on public.festival_sessions (leader_profile_id) where leader_profile_id is not null;
create index festival_session_collections_collection_idx
  on public.festival_session_collections (festival_collection_id);
create index festival_session_collections_order_idx
  on public.festival_session_collections (festival_id, session_id, editorial_order, festival_collection_id);
create index festival_hubs_curator_profile_idx
  on public.festival_hubs (curator_profile_id) where curator_profile_id is not null;
create index festival_collections_profile_idx
  on public.festival_collections (profile_id) where profile_id is not null;

create function public.validate_festival_hub_timezone()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if not exists (select 1 from pg_catalog.pg_timezone_names where name = new.timezone) then
    raise exception using errcode = '22023', message = 'invalid festival timezone';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger validate_festival_hub_timezone_before_write
before insert or update on public.festival_hubs
for each row execute function public.validate_festival_hub_timezone();

create function public.validate_festival_settings()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.mode_enabled and not exists (
    select 1 from public.festival_hubs
    where id = new.selected_festival_id and lifecycle = 'published'
  ) then
    raise exception using errcode = '23514', message = 'festival mode requires a selected published festival';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger validate_festival_settings_before_write
before insert or update on public.festival_settings
for each row execute function public.validate_festival_settings();

create function public.disable_festival_mode_for_unpublished_selection()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.lifecycle = 'published' and new.lifecycle <> 'published' then
    update public.festival_settings
    set mode_enabled = false, updated_at = now()
    where selected_festival_id = new.id and mode_enabled;
  end if;
  return new;
end;
$$;

create trigger disable_festival_mode_after_withdrawal
after update of lifecycle on public.festival_hubs
for each row execute function public.disable_festival_mode_for_unpublished_selection();

alter table public.festival_hubs enable row level security;
alter table public.festival_collections enable row level security;
alter table public.festival_sessions enable row level security;
alter table public.festival_session_collections enable row level security;
alter table public.festival_settings enable row level security;

revoke all on public.festival_hubs, public.festival_collections, public.festival_sessions,
  public.festival_session_collections, public.festival_settings from public, anon, authenticated;
grant select on public.festival_hubs, public.festival_collections, public.festival_sessions,
  public.festival_session_collections, public.festival_settings to anon, authenticated;
grant insert, update, delete on public.festival_hubs, public.festival_collections,
  public.festival_sessions, public.festival_session_collections to authenticated;
grant update (mode_enabled, selected_festival_id) on public.festival_settings to authenticated;
grant usage, select on sequence public.festival_hubs_id_seq, public.festival_collections_id_seq,
  public.festival_sessions_id_seq to authenticated;

create policy "public can read published festival hubs"
on public.festival_hubs for select to anon, authenticated
using (
  lifecycle in ('published', 'archived')
  or exists (
    select 1 from public.app_admins
    where user_id = (select auth.uid()) and role = 'owner'
  )
);

create policy "public can read visible festival collections"
on public.festival_collections for select to anon, authenticated
using (
  exists (
    select 1 from public.festival_hubs h
    where h.id = festival_id and h.lifecycle in ('published', 'archived')
  )
  and exists (
    select 1 from public.learning_lists l
    where l.id = learning_list_id and l.visibility = 'public'
  )
  or exists (
    select 1 from public.app_admins
    where user_id = (select auth.uid()) and role = 'owner'
  )
);

create policy "public can read visible festival sessions"
on public.festival_sessions for select to anon, authenticated
using (
  exists (
    select 1 from public.festival_hubs h
    where h.id = festival_id and h.lifecycle in ('published', 'archived')
  )
  or exists (
    select 1 from public.app_admins
    where user_id = (select auth.uid()) and role = 'owner'
  )
);

create policy "public can read visible festival session collections"
on public.festival_session_collections for select to anon, authenticated
using (
  exists (
    select 1
    from public.festival_sessions s
    join public.festival_hubs h on h.id = s.festival_id
    join public.festival_collections c
      on c.id = festival_collection_id and c.festival_id = festival_session_collections.festival_id
    join public.learning_lists l on l.id = c.learning_list_id
    where s.id = session_id
      and s.festival_id = festival_session_collections.festival_id
      and h.lifecycle in ('published', 'archived')
      and l.visibility = 'public'
  )
  or exists (
    select 1 from public.app_admins
    where user_id = (select auth.uid()) and role = 'owner'
  )
);

create policy "public can read active festival settings"
on public.festival_settings for select to anon, authenticated
using (
  mode_enabled
  and exists (
    select 1 from public.festival_hubs h
    where h.id = selected_festival_id and h.lifecycle = 'published'
  )
  or exists (
    select 1 from public.app_admins
    where user_id = (select auth.uid()) and role = 'owner'
  )
);

create policy "owner manages festival hubs"
on public.festival_hubs for all to authenticated
using (exists (
  select 1 from public.app_admins
  where user_id = (select auth.uid()) and role = 'owner'
))
with check (exists (
  select 1 from public.app_admins
  where user_id = (select auth.uid()) and role = 'owner'
));

create policy "owner manages festival collections"
on public.festival_collections for all to authenticated
using (exists (
  select 1 from public.app_admins
  where user_id = (select auth.uid()) and role = 'owner'
))
with check (exists (
  select 1 from public.app_admins
  where user_id = (select auth.uid()) and role = 'owner'
));

create policy "owner manages festival sessions"
on public.festival_sessions for all to authenticated
using (exists (
  select 1 from public.app_admins
  where user_id = (select auth.uid()) and role = 'owner'
))
with check (exists (
  select 1 from public.app_admins
  where user_id = (select auth.uid()) and role = 'owner'
));

create policy "owner manages festival session collections"
on public.festival_session_collections for all to authenticated
using (exists (
  select 1 from public.app_admins
  where user_id = (select auth.uid()) and role = 'owner'
))
with check (exists (
  select 1 from public.app_admins
  where user_id = (select auth.uid()) and role = 'owner'
));

create policy "owner updates festival settings"
on public.festival_settings for update to authenticated
using (exists (
  select 1 from public.app_admins
  where user_id = (select auth.uid()) and role = 'owner'
))
with check (exists (
  select 1 from public.app_admins
  where user_id = (select auth.uid()) and role = 'owner'
));

revoke execute on function public.validate_festival_hub_timezone(),
  public.validate_festival_settings(),
  public.disable_festival_mode_for_unpublished_selection() from public, anon, authenticated;
