create table if not exists public.learning_list_bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  learning_list_id bigint not null references public.learning_lists(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, learning_list_id)
);

alter table public.learning_list_bookmarks enable row level security;

drop policy if exists "Users can select their own list bookmarks"
  on public.learning_list_bookmarks;
create policy "Users can select their own list bookmarks"
  on public.learning_list_bookmarks
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own public list bookmarks"
  on public.learning_list_bookmarks;
create policy "Users can insert their own public list bookmarks"
  on public.learning_list_bookmarks
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and exists (
      select 1
      from public.learning_lists
      where learning_lists.id = learning_list_bookmarks.learning_list_id
        and learning_lists.visibility = 'public'
        and learning_lists.user_id <> auth.uid()::text
    )
  );

drop policy if exists "Users can delete their own list bookmarks"
  on public.learning_list_bookmarks;
create policy "Users can delete their own list bookmarks"
  on public.learning_list_bookmarks
  for delete
  to authenticated
  using (auth.uid() = user_id);

create index if not exists learning_list_bookmarks_user_id_created_at_idx
  on public.learning_list_bookmarks (user_id, created_at desc);

create index if not exists learning_list_bookmarks_learning_list_id_idx
  on public.learning_list_bookmarks (learning_list_id);
